apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: common
  labels:
    deploy: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: alberth1414/eureka-server:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: common
spec:
  selector:
    app: eureka
  ports:
    - name: amqp
      protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: eureka-ingress
#  namespace: common
#spec:
#  rules:
#  - host: eurekaserver.sytes.net
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: eureka-service
#            port:
#              number: 8761
